title: 'typiespectre.github.io'
description: "Typiespectre's Blog"
baseurl: ""
url: "https://typiespectre.github.io"

# Example Site settings
google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/typiespectre">twitter</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
remote_theme: Typiespectre/jekyll-theme-console
