remote_theme: b2a3e8/jekyll-theme-console

url: "https://typiespectre.github.io"
baseurl: ""

# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/typiespectre">twitter</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
